// 이 파일은 scripts/fetch-kbl-history.mjs에 의해 자동 생성되었습니다.
import type { GameSchedule } from "./schedule";

export const SONO_SCHEDULE_2425: GameSchedule[] = [
  {
    "date": "241005",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 74,
    "opponentScore": 90,
    "venue": "울산",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 74,
    "awayScore": 90
  },
  {
    "date": "241007",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 83,
    "opponentScore": 77,
    "venue": "안양",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 77,
    "awayScore": 83
  },
  {
    "date": "241020",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 100,
    "opponentScore": 82,
    "venue": "울산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 82,
    "awayScore": 100
  },
  {
    "date": "241023",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 79,
    "opponentScore": 69,
    "venue": "부산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 69,
    "awayScore": 79
  },
  {
    "date": "241026",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 82,
    "opponentScore": 77,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 82,
    "awayScore": 77
  },
  {
    "date": "241028",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 83,
    "opponentScore": 70,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 83,
    "awayScore": 70
  },
  {
    "date": "241031",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 61,
    "opponentScore": 69,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 61,
    "awayScore": 69
  },
  {
    "date": "241102",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 76,
    "opponentScore": 78,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 78,
    "awayScore": 76
  },
  {
    "date": "241104",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 79,
    "opponentScore": 64,
    "venue": "원주",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 64,
    "awayScore": 79
  },
  {
    "date": "241108",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 65,
    "opponentScore": 99,
    "venue": "대구",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 99,
    "awayScore": 65
  },
  {
    "date": "241110",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 71,
    "opponentScore": 91,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 91,
    "awayScore": 71
  },
  {
    "date": "241113",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 78,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 78,
    "awayScore": 80
  },
  {
    "date": "241128",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 78,
    "opponentScore": 88,
    "venue": "원주",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 88,
    "awayScore": 78
  },
  {
    "date": "241130",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 78,
    "opponentScore": 86,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 78,
    "awayScore": 86
  },
  {
    "date": "241201",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 67,
    "opponentScore": 74,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 67,
    "awayScore": 74
  },
  {
    "date": "241203",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 63,
    "opponentScore": 85,
    "venue": "대구",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 85,
    "awayScore": 63
  },
  {
    "date": "241206",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 64,
    "opponentScore": 72,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 64,
    "awayScore": 72
  },
  {
    "date": "241208",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 81,
    "opponentScore": 92,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 81,
    "awayScore": 92
  },
  {
    "date": "241213",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 73,
    "opponentScore": 82,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 73,
    "awayScore": 82
  },
  {
    "date": "241215",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 78,
    "opponentScore": 79,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 79,
    "awayScore": 78
  },
  {
    "date": "241218",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 75,
    "opponentScore": 58,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 75,
    "awayScore": 58
  },
  {
    "date": "241221",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 81,
    "opponentScore": 61,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 81,
    "awayScore": 61
  },
  {
    "date": "241225",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 87,
    "opponentScore": 81,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 87,
    "awayScore": 81
  },
  {
    "date": "241228",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 73,
    "opponentScore": 76,
    "venue": "대구",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 76,
    "awayScore": 73
  },
  {
    "date": "241229",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 67,
    "opponentScore": 84,
    "venue": "울산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 84,
    "awayScore": 67
  },
  {
    "date": "250101",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 62,
    "opponentScore": 59,
    "venue": "안양",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 59,
    "awayScore": 62
  },
  {
    "date": "250103",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 70,
    "opponentScore": 78,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 78,
    "awayScore": 70
  },
  {
    "date": "250105",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 64,
    "opponentScore": 67,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 67,
    "awayScore": 64
  },
  {
    "date": "250109",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 68,
    "opponentScore": 93,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 68,
    "awayScore": 93
  },
  {
    "date": "250111",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 70,
    "opponentScore": 73,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 70,
    "awayScore": 73
  },
  {
    "date": "250112",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 57,
    "opponentScore": 84,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 57,
    "awayScore": 84
  },
  {
    "date": "250115",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 84,
    "opponentScore": 81,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 84,
    "awayScore": 81
  },
  {
    "date": "250123",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 62,
    "opponentScore": 67,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 67,
    "awayScore": 62
  },
  {
    "date": "250125",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 56,
    "opponentScore": 76,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 56,
    "awayScore": 76
  },
  {
    "date": "250128",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 69,
    "opponentScore": 94,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 69,
    "awayScore": 94
  },
  {
    "date": "250131",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 73,
    "opponentScore": 78,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 78,
    "awayScore": 73
  },
  {
    "date": "250202",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 86,
    "opponentScore": 82,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 86,
    "awayScore": 82
  },
  {
    "date": "250207",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 63,
    "opponentScore": 77,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 77,
    "awayScore": 63
  },
  {
    "date": "250209",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 76,
    "opponentScore": 63,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 63,
    "awayScore": 76
  },
  {
    "date": "250211",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 80,
    "opponentScore": 101,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 80,
    "awayScore": 101
  },
  {
    "date": "250226",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 95,
    "opponentScore": 85,
    "venue": "부산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 85,
    "awayScore": 95
  },
  {
    "date": "250301",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 92,
    "opponentScore": 82,
    "venue": "원주",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 82,
    "awayScore": 92
  },
  {
    "date": "250302",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 79,
    "opponentScore": 88,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 79,
    "awayScore": 88
  },
  {
    "date": "250307",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 56,
    "opponentScore": 71,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 56,
    "awayScore": 71
  },
  {
    "date": "250309",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 79,
    "opponentScore": 91,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 91,
    "awayScore": 79
  },
  {
    "date": "250313",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 63,
    "opponentScore": 69,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 69,
    "awayScore": 63
  },
  {
    "date": "250315",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 84,
    "opponentScore": 86,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 84,
    "awayScore": 86
  },
  {
    "date": "250320",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 90,
    "opponentScore": 85,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 90,
    "awayScore": 85
  },
  {
    "date": "250322",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 84,
    "opponentScore": 59,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 84,
    "awayScore": 59
  },
  {
    "date": "250325",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 84,
    "opponentScore": 93,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 93,
    "awayScore": 84
  },
  {
    "date": "250327",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 81,
    "opponentScore": 90,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 90,
    "awayScore": 81
  },
  {
    "date": "250329",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 79,
    "opponentScore": 94,
    "venue": "울산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 94,
    "awayScore": 79
  },
  {
    "date": "250402",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 85,
    "opponentScore": 98,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 98,
    "awayScore": 85
  },
  {
    "date": "250404",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 86,
    "opponentScore": 70,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 86,
    "awayScore": 70
  },
  {
    "date": "250406",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 96,
    "opponentScore": 71,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 71,
    "awayScore": 96
  },
  {
    "date": "250408",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 101,
    "opponentScore": 99,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 101,
    "awayScore": 99
  }
];
