// 이 파일은 scripts/fetch-kbl.mjs에 의해 자동 생성되었습니다.
export interface GameSchedule {
  date: string;
  opponentName: string;
  opponentCity: string;
  sonoScore: number;
  opponentScore: number;
  venue: string;
  resultIcon: string;
  isHome: boolean;
  homeTeamName: string;
  awayTeamName: string;
  homeScore: number;
  awayScore: number;
}

export const SONO_SCHEDULE_2526: GameSchedule[] = [
  {
    "date": "250920",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 66,
    "opponentScore": 77,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 77,
    "awayScore": 66
  },
  {
    "date": "250927",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 68,
    "opponentScore": 79,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 68,
    "awayScore": 79
  },
  {
    "date": "251004",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 50,
    "opponentScore": 69,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 69,
    "awayScore": 50
  },
  {
    "date": "251005",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 72,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 72,
    "awayScore": 80
  },
  {
    "date": "251008",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 82,
    "opponentScore": 78,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 82,
    "awayScore": 78
  },
  {
    "date": "251010",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 74,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 74,
    "awayScore": 80
  },
  {
    "date": "251012",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 86,
    "opponentScore": 80,
    "venue": "대구",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 80,
    "awayScore": 86
  },
  {
    "date": "251018",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 76,
    "opponentScore": 83,
    "venue": "원주",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 83,
    "awayScore": 76
  },
  {
    "date": "251019",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 58,
    "opponentScore": 64,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 58,
    "awayScore": 64
  },
  {
    "date": "251024",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 71,
    "opponentScore": 77,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 77,
    "awayScore": 71
  },
  {
    "date": "251026",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 83,
    "opponentScore": 85,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 85,
    "awayScore": 83
  },
  {
    "date": "251101",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 74,
    "opponentScore": 64,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 74,
    "awayScore": 64
  },
  {
    "date": "251102",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 75,
    "opponentScore": 78,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 78,
    "awayScore": 75
  },
  {
    "date": "251106",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 68,
    "opponentScore": 74,
    "venue": "울산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 74,
    "awayScore": 68
  },
  {
    "date": "251109",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 85,
    "opponentScore": 63,
    "venue": "수원",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 63,
    "awayScore": 85
  },
  {
    "date": "251113",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 93,
    "opponentScore": 82,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 93,
    "awayScore": 82
  },
  {
    "date": "251116",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 72,
    "opponentScore": 75,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 72,
    "awayScore": 75
  },
  {
    "date": "251118",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 93,
    "opponentScore": 82,
    "venue": "원주",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 82,
    "awayScore": 93
  },
  {
    "date": "251120",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 85,
    "opponentScore": 74,
    "venue": "부산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 74,
    "awayScore": 85
  },
  {
    "date": "251205",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 72,
    "opponentScore": 79,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 72,
    "awayScore": 79
  },
  {
    "date": "251207",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 75,
    "opponentScore": 59,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 59,
    "awayScore": 75
  },
  {
    "date": "251209",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 78,
    "opponentScore": 87,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 78,
    "awayScore": 87
  },
  {
    "date": "251214",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 75,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 75,
    "awayScore": 80
  },
  {
    "date": "251216",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 85,
    "opponentScore": 86,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 85,
    "awayScore": 86
  },
  {
    "date": "251220",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 81,
    "opponentScore": 108,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 108,
    "awayScore": 81
  },
  {
    "date": "251225",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 74,
    "opponentScore": 64,
    "venue": "울산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 64,
    "awayScore": 74
  },
  {
    "date": "251227",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 92,
    "opponentScore": 98,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 92,
    "awayScore": 98
  },
  {
    "date": "251229",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 70,
    "opponentScore": 77,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 70,
    "awayScore": 77
  },
  {
    "date": "260101",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 70,
    "opponentScore": 69,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 70,
    "awayScore": 69
  },
  {
    "date": "260103",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 64,
    "opponentScore": 76,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 64,
    "awayScore": 76
  },
  {
    "date": "260105",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 77,
    "opponentScore": 67,
    "venue": "대구",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 67,
    "awayScore": 77
  },
  {
    "date": "260110",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 74,
    "opponentScore": 87,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 87,
    "awayScore": 74
  },
  {
    "date": "260112",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 90,
    "opponentScore": 96,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 96,
    "awayScore": 90
  },
  {
    "date": "260115",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 90,
    "opponentScore": 77,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 90,
    "awayScore": 77
  },
  {
    "date": "260123",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 64,
    "opponentScore": 65,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 65,
    "awayScore": 64
  },
  {
    "date": "260125",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 91,
    "opponentScore": 77,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 77,
    "awayScore": 91
  },
  {
    "date": "260127",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 99,
    "opponentScore": 54,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 99,
    "awayScore": 54
  },
  {
    "date": "260131",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 59,
    "opponentScore": 79,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 79,
    "awayScore": 59
  },
  {
    "date": "260201",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 80,
    "opponentScore": 62,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 80,
    "awayScore": 62
  },
  {
    "date": "260204",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 95,
    "opponentScore": 89,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 95,
    "awayScore": 89
  },
  {
    "date": "260207",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 92,
    "opponentScore": 78,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 92,
    "awayScore": 78
  },
  {
    "date": "260211",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 64,
    "opponentScore": 81,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 81,
    "awayScore": 64
  },
  {
    "date": "260214",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 87,
    "opponentScore": 76,
    "venue": "울산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 76,
    "awayScore": 87
  },
  {
    "date": "260216",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 79,
    "opponentScore": 62,
    "venue": "창원",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 62,
    "awayScore": 79
  },
  {
    "date": "260219",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 86,
    "opponentScore": 64,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 86,
    "awayScore": 64
  },
  {
    "date": "260305",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 75,
    "opponentScore": 73,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 75,
    "awayScore": 73
  },
  {
    "date": "260307",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 95,
    "opponentScore": 81,
    "venue": "원주",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 81,
    "awayScore": 95
  },
  {
    "date": "260311",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 74,
    "opponentScore": 70,
    "venue": "창원",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 70,
    "awayScore": 74
  },
  {
    "date": "260315",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 98,
    "opponentScore": 75,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 98,
    "awayScore": 75
  },
  {
    "date": "260319",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 111,
    "opponentScore": 77,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 111,
    "awayScore": 77
  },
  {
    "date": "260321",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 90,
    "opponentScore": 86,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 90,
    "awayScore": 86
  },
  {
    "date": "260325",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 78,
    "opponentScore": 77,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 77,
    "awayScore": 78
  },
  {
    "date": "260328",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 81,
    "opponentScore": 92,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 81,
    "awayScore": 92
  },
  {
    "date": "260402",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 76,
    "opponentScore": 78,
    "venue": "대구",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 78,
    "awayScore": 76
  },
  {
    "date": "260405",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 65,
    "opponentScore": 61,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 65,
    "awayScore": 61
  },
  {
    "date": "260408",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 72,
    "opponentScore": 76,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 76,
    "awayScore": 72
  },
  {
    "date": "260412",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 105,
    "opponentScore": 76,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 76,
    "awayScore": 105
  },
  {
    "date": "260414",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 80,
    "opponentScore": 72,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 72,
    "awayScore": 80
  },
  {
    "date": "260416",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 66,
    "opponentScore": 65,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 66,
    "awayScore": 65
  },
  {
    "date": "260423",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 69,
    "opponentScore": 63,
    "venue": "창원",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 63,
    "awayScore": 69
  },
  {
    "date": "260425",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 85,
    "opponentScore": 76,
    "venue": "창원",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 76,
    "awayScore": 85
  },
  {
    "date": "260427",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 90,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 90,
    "awayScore": 80
  },
  {
    "date": "260505",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 67,
    "opponentScore": 75,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 67,
    "awayScore": 75
  },
  {
    "date": "260507",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 78,
    "opponentScore": 96,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 78,
    "awayScore": 96
  },
  {
    "date": "260509",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 87,
    "opponentScore": 88,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 88,
    "awayScore": 87
  },
  {
    "date": "260510",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 81,
    "opponentScore": 80,
    "venue": "부산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 80,
    "awayScore": 81
  },
  {
    "date": "260513",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 68,
    "opponentScore": 76,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 68,
    "awayScore": 76
  }
];
