// 이 파일은 scripts/fetch-kbl-2627.mjs에 의해 자동 생성되었습니다.
import type { GameSchedule } from "./schedule";

export const SONO_SCHEDULE_2627: GameSchedule[] = [
  {
    "date": "261003",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 82,
    "opponentScore": 73,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 82,
    "awayScore": 73
  },
  {
    "date": "261004",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 86,
    "opponentScore": 95,
    "venue": "원주",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 95,
    "awayScore": 86
  },
  {
    "date": "261009",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "수원",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261011",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "서울",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261013",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "안양",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261016",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261018",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "서울",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261021",
    "opponentName": "TSG 고스트호크스",
    "opponentCity": "기타",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "기타",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "TSG 고스트호크스",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261024",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261026",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261030",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261101",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261103",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "부산",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261107",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "창원",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261110",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "울산",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261112",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "대구",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261115",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261118",
    "opponentName": "사우스 고비 브롱코스",
    "opponentCity": "기타",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "사우스 고비 브롱코스",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261203",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261205",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261209",
    "opponentName": "알바크 도쿄",
    "opponentCity": "기타",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "알바크 도쿄",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261212",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "안양",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261215",
    "opponentName": "TSG 고스트호크스",
    "opponentCity": "기타",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "TSG 고스트호크스",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261218",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "서울",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261220",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261223",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261225",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261227",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "창원",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "261231",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "수원",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270102",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270103",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "원주",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270105",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270109",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "대구",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270110",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "부산",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270113",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270117",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270120",
    "opponentName": "알바크 도쿄",
    "opponentCity": "기타",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "기타",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "알바크 도쿄",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270123",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270125",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "울산",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270127",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "창원",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270203",
    "opponentName": "사우스 고비 브롱코스",
    "opponentCity": "기타",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "기타",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "사우스 고비 브롱코스",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270206",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270208",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "안양",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270211",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "울산",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270213",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "부산",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270216",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270218",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270304",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "원주",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270306",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270313",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "서울",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270314",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270317",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "대구",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270321",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "수원",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270323",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270331",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "서울",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270403",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "서울",
    "resultIcon": "⏳",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270405",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270407",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270409",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 0,
    "awayScore": 0
  },
  {
    "date": "270411",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 0,
    "opponentScore": 0,
    "venue": "고양",
    "resultIcon": "⏳",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 0,
    "awayScore": 0
  }
];
