// 이 파일은 scripts/fetch-kbl-history.mjs에 의해 자동 생성되었습니다.
import type { GameSchedule } from "./schedule";

export const SONO_SCHEDULE_2324: GameSchedule[] = [
  {
    "date": "231010",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 90,
    "opponentScore": 100,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 90,
    "awayScore": 100
  },
  {
    "date": "231012",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 80,
    "opponentScore": 88,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 88,
    "awayScore": 80
  },
  {
    "date": "231022",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 89,
    "opponentScore": 110,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 89,
    "awayScore": 110
  },
  {
    "date": "231024",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 79,
    "opponentScore": 90,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 79,
    "awayScore": 90
  },
  {
    "date": "231027",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 78,
    "opponentScore": 98,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 98,
    "awayScore": 78
  },
  {
    "date": "231029",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 99,
    "opponentScore": 88,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 99,
    "awayScore": 88
  },
  {
    "date": "231102",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 73,
    "opponentScore": 87,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 87,
    "awayScore": 73
  },
  {
    "date": "231104",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 84,
    "opponentScore": 82,
    "venue": "안양",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 82,
    "awayScore": 84
  },
  {
    "date": "231106",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 65,
    "opponentScore": 101,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 101,
    "awayScore": 65
  },
  {
    "date": "231111",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 100,
    "opponentScore": 90,
    "venue": "대구",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 90,
    "awayScore": 100
  },
  {
    "date": "231112",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 93,
    "opponentScore": 84,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 93,
    "awayScore": 84
  },
  {
    "date": "231117",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 69,
    "opponentScore": 78,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 78,
    "awayScore": 69
  },
  {
    "date": "231119",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 91,
    "opponentScore": 99,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 91,
    "awayScore": 99
  },
  {
    "date": "231125",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 49,
    "opponentScore": 80,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 80,
    "awayScore": 49
  },
  {
    "date": "231126",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 84,
    "opponentScore": 77,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 84,
    "awayScore": 77
  },
  {
    "date": "231128",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 86,
    "opponentScore": 82,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 86,
    "awayScore": 82
  },
  {
    "date": "231201",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 78,
    "opponentScore": 64,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 64,
    "awayScore": 78
  },
  {
    "date": "231203",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 71,
    "opponentScore": 66,
    "venue": "울산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 66,
    "awayScore": 71
  },
  {
    "date": "231205",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 81,
    "opponentScore": 86,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 86,
    "awayScore": 81
  },
  {
    "date": "231208",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 74,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 74,
    "awayScore": 80
  },
  {
    "date": "231210",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 76,
    "opponentScore": 84,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 76,
    "awayScore": 84
  },
  {
    "date": "231215",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 64,
    "opponentScore": 82,
    "venue": "수원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KT",
    "awayTeamName": "소노",
    "homeScore": 82,
    "awayScore": 64
  },
  {
    "date": "231217",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 61,
    "opponentScore": 69,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 69,
    "awayScore": 61
  },
  {
    "date": "231221",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 70,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "SK",
    "homeScore": 70,
    "awayScore": 80
  },
  {
    "date": "231223",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 58,
    "opponentScore": 92,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "DB",
    "homeScore": 58,
    "awayScore": 92
  },
  {
    "date": "231224",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 72,
    "opponentScore": 92,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 72,
    "awayScore": 92
  },
  {
    "date": "231228",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 85,
    "opponentScore": 81,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 85,
    "awayScore": 81
  },
  {
    "date": "231230",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 67,
    "opponentScore": 86,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 67,
    "awayScore": 86
  },
  {
    "date": "231231",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 72,
    "opponentScore": 79,
    "venue": "창원",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "LG",
    "awayTeamName": "소노",
    "homeScore": 79,
    "awayScore": 72
  },
  {
    "date": "240102",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 94,
    "opponentScore": 88,
    "venue": "원주",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 88,
    "awayScore": 94
  },
  {
    "date": "240105",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 61,
    "opponentScore": 87,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 87,
    "awayScore": 61
  },
  {
    "date": "240107",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 74,
    "opponentScore": 83,
    "venue": "부산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "KCC",
    "awayTeamName": "소노",
    "homeScore": 83,
    "awayScore": 74
  },
  {
    "date": "240117",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 93,
    "opponentScore": 86,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "정관장",
    "homeScore": 93,
    "awayScore": 86
  },
  {
    "date": "240120",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 73,
    "opponentScore": 92,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 73,
    "awayScore": 92
  },
  {
    "date": "240123",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 87,
    "opponentScore": 79,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 87,
    "awayScore": 79
  },
  {
    "date": "240126",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 85,
    "opponentScore": 93,
    "venue": "울산",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 93,
    "awayScore": 85
  },
  {
    "date": "240128",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 77,
    "opponentScore": 76,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "가스공사",
    "homeScore": 77,
    "awayScore": 76
  },
  {
    "date": "240130",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 70,
    "opponentScore": 74,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 70,
    "awayScore": 74
  },
  {
    "date": "240201",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 77,
    "opponentScore": 80,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 77,
    "awayScore": 80
  },
  {
    "date": "240203",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 66,
    "opponentScore": 83,
    "venue": "대구",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 83,
    "awayScore": 66
  },
  {
    "date": "240205",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 89,
    "opponentScore": 92,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 89,
    "awayScore": 92
  },
  {
    "date": "240209",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 89,
    "opponentScore": 99,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "삼성",
    "homeScore": 89,
    "awayScore": 99
  },
  {
    "date": "240211",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 74,
    "opponentScore": 89,
    "venue": "원주",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 89,
    "awayScore": 74
  },
  {
    "date": "240214",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 95,
    "opponentScore": 77,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 95,
    "awayScore": 77
  },
  {
    "date": "240228",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 66,
    "opponentScore": 98,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 98,
    "awayScore": 66
  },
  {
    "date": "240301",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 83,
    "opponentScore": 73,
    "venue": "울산",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "현대모비스",
    "awayTeamName": "소노",
    "homeScore": 73,
    "awayScore": 83
  },
  {
    "date": "240303",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 87,
    "opponentScore": 92,
    "venue": "안양",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 92,
    "awayScore": 87
  },
  {
    "date": "240305",
    "opponentName": "KCC",
    "opponentCity": "부산",
    "sonoScore": 85,
    "opponentScore": 117,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KCC",
    "homeScore": 85,
    "awayScore": 117
  },
  {
    "date": "240309",
    "opponentName": "삼성",
    "opponentCity": "서울",
    "sonoScore": 86,
    "opponentScore": 92,
    "venue": "서울",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "삼성",
    "awayTeamName": "소노",
    "homeScore": 92,
    "awayScore": 86
  },
  {
    "date": "240313",
    "opponentName": "정관장",
    "opponentCity": "안양",
    "sonoScore": 94,
    "opponentScore": 80,
    "venue": "안양",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "정관장",
    "awayTeamName": "소노",
    "homeScore": 80,
    "awayScore": 94
  },
  {
    "date": "240315",
    "opponentName": "LG",
    "opponentCity": "창원",
    "sonoScore": 64,
    "opponentScore": 95,
    "venue": "고양",
    "resultIcon": "💔",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "LG",
    "homeScore": 64,
    "awayScore": 95
  },
  {
    "date": "240317",
    "opponentName": "가스공사",
    "opponentCity": "대구",
    "sonoScore": 82,
    "opponentScore": 81,
    "venue": "대구",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "가스공사",
    "awayTeamName": "소노",
    "homeScore": 81,
    "awayScore": 82
  },
  {
    "date": "240319",
    "opponentName": "SK",
    "opponentCity": "서울",
    "sonoScore": 75,
    "opponentScore": 62,
    "venue": "서울",
    "resultIcon": "🩵",
    "isHome": false,
    "homeTeamName": "SK",
    "awayTeamName": "소노",
    "homeScore": 62,
    "awayScore": 75
  },
  {
    "date": "240322",
    "opponentName": "현대모비스",
    "opponentCity": "울산",
    "sonoScore": 102,
    "opponentScore": 87,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "현대모비스",
    "homeScore": 102,
    "awayScore": 87
  },
  {
    "date": "240324",
    "opponentName": "DB",
    "opponentCity": "원주",
    "sonoScore": 84,
    "opponentScore": 86,
    "venue": "원주",
    "resultIcon": "💔",
    "isHome": false,
    "homeTeamName": "DB",
    "awayTeamName": "소노",
    "homeScore": 86,
    "awayScore": 84
  },
  {
    "date": "240331",
    "opponentName": "KT",
    "opponentCity": "수원",
    "sonoScore": 95,
    "opponentScore": 91,
    "venue": "고양",
    "resultIcon": "🩵",
    "isHome": true,
    "homeTeamName": "소노",
    "awayTeamName": "KT",
    "homeScore": 95,
    "awayScore": 91
  }
];
