import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const kblCourt = localFont({
  src: "../assets/fonts/KBLCourt_EB.woff2",
  variable: "--font-kbl-court",
});

const kblJump1 = localFont({
  src: "../assets/fonts/KBLJump_R.woff2",
  variable: "--font-kbl-jump1",
});

const kblJump2 = localFont({
  src: "../assets/fonts/KBLJump_B.woff2",
  variable: "--font-kbl-jump2",
});

const kblJump3 = localFont({
  src: "../assets/fonts/KBLJump_EB_Condensed.woff2",
  variable: "--font-kbl-jump3",
});

const kblJump4 = localFont({
  src: "../assets/fonts/KBLJump_EB_Extended.woff2",
  variable: "--font-kbl-jump4",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kblCourt.variable} ${kblJump1.variable} ${kblJump2.variable} ${kblJump3.variable} ${kblJump4.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
